# A short, descriptive name of this building block collection
name: Open Science Workflows Building Blocks

# Short abstract for this collection (optional)
abstract: |
  Building Blocks for FAIR Open Science - profiles of OGC API Processes and various metadata standards to support open, transparent, interoperable and reproducible scientific workflows..
# Description for this collection (optional)
description: |
  This repository is initially aimed to support the [Open Science Persistent Demonstrator](https://www.ogc.org/initiatives/open-science/) pilot, but may be further developed as a set of standards with appropriate working group governance.

# Customize the following prefix (will be prepended to the path of the building blocks):
identifier-prefix: ogc.osc.

# List of imports ("default" is an alias for the main OGC Building Blocks Register)
imports:
  - default
  - https://ogcincubator.github.io/bblocks-ogcapi-records
  - https://ogcincubator.github.io/bblocks-ogcapi-processes
  - https://ogcincubator.github.io/prov-cwl/
  - https://ogcincubator.github.io/bblocks-wf4ever/
  - https://ogcincubator.github.io/bblocks-stac
  - https://ogcincubator.github.io/cross-domain-model

# Whether to enable the (highly experimental) downcompiling of JSON schemas to an OpenAPI 3.0-compatible
# version
schema-oas30-downcompile: False

# SPARQL configuration (optional)
#   Authentication can be set through the sparql_username and sparql_password GitHub Workflow inputs
#   (see .github/workflow/process-bblocks.yml)
#
# sparql:
#   push: https://example.com/gsp           # SPARQL Graph Store Protocol endpoint for uploading data
#   graph: https://my.bblocks.example.com/  # SPARQL Graph where data will be uploaded
#                                           #  if left empty, the base URL for the publication will be used
#   query: https://example.com/sparql       # SPARQL query endpoint where data will be available
#   resources:                              # Additional resources to upload apart from building block metadata
#      ontologies: true                     #   Whether to upload ontology files to the triplestore